# Generated by Django 5.0.6 on 2024-10-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelBase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodeldictionaryconfigmodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='modeldictionaryconfigmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
