# Generated by Django 5.0.6 on 2024-10-19 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelBase', '0002_historicalmodeldictionaryconfigmodel_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmodeldictionaryconfigmodel',
            name='code',
            field=models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator(message='Only accepts letters (a-z, A-Z), numbers (0-9), and underscores (_).', regex='^[a-zA-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='modeldictionaryconfigmodel',
            name='code',
            field=models.CharField(max_length=63, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Only accepts letters (a-z, A-Z), numbers (0-9), and underscores (_).', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
