# Generated by Django 5.0.9 on 2025-03-09 23:28

import base.models
import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryModel',
            fields=[
                ('code', models.CharField(max_length=63, primary_key=True, serialize=False, validators=[base.models.validate_dictionary_code, django.core.validators.RegexValidator(message='Start with letters, and only accepts letters (a-z, A-Z), numbers (0-9), dashes (-), and underscores (_).', regex='^[a-zA-Z][a-zA-Z0-9_]*$')])),
                ('description', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/')),
                ('name', models.CharField(max_length=127)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(default='System', max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalModelDictionaryItemsConfigModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('backend_field_name', models.CharField(max_length=127)),
                ('field_label', models.CharField(max_length=255)),
                ('index', models.PositiveSmallIntegerField(verbose_name='index for field ordering')),
                ('add_fieldsets', models.BooleanField(default=False, verbose_name='fields for create records')),
                ('list_display', models.BooleanField(default=True, verbose_name='fields for display in list')),
                ('fieldsets', models.BooleanField(default=True, verbose_name='fields for display in details')),
                ('edit_fieldsets', models.BooleanField(default=False, verbose_name='fields for enable edit')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical model dictionary items config model',
                'verbose_name_plural': 'historical model dictionary items config models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ModelDictionaryConfigModel',
            fields=[
                ('code', models.CharField(max_length=63, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Start with letters, and only accepts letters (a-z, A-Z), numbers (0-9), and underscores (_).', regex='^[a-zA-Z][a-zA-Z0-9_]*$')])),
                ('description', models.CharField(max_length=511)),
                ('backend_app_label', models.CharField(max_length=127)),
                ('backend_app_model', models.CharField(max_length=127)),
                ('model_label', models.CharField(default='model', max_length=255)),
                ('pk_field_name', models.CharField(blank=True, default='id', max_length=63, null=True)),
                ('default_order_by', models.CharField(blank=True, default="['id']", max_length=255, null=True, verbose_name='a list of fields that used for ordering the records in list view')),
                ('unique_keys', models.CharField(blank=True, default="['id']", max_length=255, null=True, verbose_name='a list of fields that make the record unique')),
                ('fk_fields', models.JSONField(blank=True, help_text='format [{"model": "model","field_name": "field_name","label": "label"}] ', max_length=511, null=True, verbose_name='Are FK fields in the table or other table with one to one or many to one relationship')),
                ('fk_multi_fields', models.JSONField(blank=True, help_text='format [{"model": "model","field_name": "field_name","label": "label"}]', max_length=511, null=True, verbose_name='As FK field in the table or other tables with one to many or manay to many relationship')),
                ('sub_tables', models.JSONField(blank=True, help_text='related table to create, display, or modify format [{"id_filter_name": "id_filter_name", "dictionary_code": "dictionary_code", "label": "label"}] ** id_filter_name should be the field name__id in the sub table model', max_length=511, null=True, verbose_name='related table to create, display, or modify')),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelDictionaryItemsConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_field_name', models.CharField(max_length=127)),
                ('field_label', models.CharField(max_length=255)),
                ('index', models.PositiveSmallIntegerField(verbose_name='index for field ordering')),
                ('add_fieldsets', models.BooleanField(default=False, verbose_name='fields for create records')),
                ('list_display', models.BooleanField(default=True, verbose_name='fields for display in list')),
                ('fieldsets', models.BooleanField(default=True, verbose_name='fields for display in details')),
                ('edit_fieldsets', models.BooleanField(default=False, verbose_name='fields for enable edit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DictionaryItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=63, null=True)),
                ('category', models.CharField(blank=True, max_length=63, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dictionary_item_dictionary', to='base.dictionarymodel')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dictionary_item_sub_category', to='base.dictionarymodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalDictionaryItemModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=63, null=True)),
                ('category', models.CharField(blank=True, max_length=63, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('dictionary', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.dictionarymodel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.dictionarymodel')),
            ],
            options={
                'verbose_name': 'historical dictionary item model',
                'verbose_name_plural': 'historical dictionary item models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDictionaryModel',
            fields=[
                ('code', models.CharField(db_index=True, max_length=63, validators=[base.models.validate_dictionary_code, django.core.validators.RegexValidator(message='Start with letters, and only accepts letters (a-z, A-Z), numbers (0-9), dashes (-), and underscores (_).', regex='^[a-zA-Z][a-zA-Z0-9_]*$')])),
                ('description', models.CharField(db_index=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical dictionary model',
                'verbose_name_plural': 'historical dictionary models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFileModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('file', models.TextField(max_length=100)),
                ('name', models.CharField(max_length=127)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.CharField(default='System', max_length=150)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical file model',
                'verbose_name_plural': 'historical file models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalModelDictionaryConfigModel',
            fields=[
                ('code', models.CharField(db_index=True, max_length=63, validators=[django.core.validators.RegexValidator(message='Start with letters, and only accepts letters (a-z, A-Z), numbers (0-9), and underscores (_).', regex='^[a-zA-Z][a-zA-Z0-9_]*$')])),
                ('description', models.CharField(max_length=511)),
                ('backend_app_label', models.CharField(max_length=127)),
                ('backend_app_model', models.CharField(max_length=127)),
                ('model_label', models.CharField(default='model', max_length=255)),
                ('pk_field_name', models.CharField(blank=True, default='id', max_length=63, null=True)),
                ('default_order_by', models.CharField(blank=True, default="['id']", max_length=255, null=True, verbose_name='a list of fields that used for ordering the records in list view')),
                ('unique_keys', models.CharField(blank=True, default="['id']", max_length=255, null=True, verbose_name='a list of fields that make the record unique')),
                ('fk_fields', models.JSONField(blank=True, help_text='format [{"model": "model","field_name": "field_name","label": "label"}] ', max_length=511, null=True, verbose_name='Are FK fields in the table or other table with one to one or many to one relationship')),
                ('fk_multi_fields', models.JSONField(blank=True, help_text='format [{"model": "model","field_name": "field_name","label": "label"}]', max_length=511, null=True, verbose_name='As FK field in the table or other tables with one to many or manay to many relationship')),
                ('sub_tables', models.JSONField(blank=True, help_text='related table to create, display, or modify format [{"id_filter_name": "id_filter_name", "dictionary_code": "dictionary_code", "label": "label"}] ** id_filter_name should be the field name__id in the sub table model', max_length=511, null=True, verbose_name='related table to create, display, or modify')),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical model dictionary config model',
                'verbose_name_plural': 'historical model dictionary config models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
