# Generated by Django 5.0.9 on 2025-03-09 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('jsonForm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmodeldictionaryconfigmodel',
            name='json_form',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jsonForm.formtemplate'),
        ),
        migrations.AddField(
            model_name='historicalmodeldictionaryitemsconfigmodel',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modeldictionaryconfigmodel',
            name='json_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonForm.formtemplate'),
        ),
        migrations.AddField(
            model_name='historicalmodeldictionaryitemsconfigmodel',
            name='dictionary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.modeldictionaryconfigmodel'),
        ),
        migrations.AddField(
            model_name='modeldictionaryitemsconfigmodel',
            name='dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dictionary_item_dictionary', to='base.modeldictionaryconfigmodel'),
        ),
    ]
